# -*- mode: python ; coding: utf-8 -*-
import sys

block_cipher = None

if sys.platform == "linux":
    BINARIES=[('/usr/bin/sox', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/libsox.so.3.0.0', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_pvf.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_lpc10.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_gsm.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_fap.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_sndfile.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_vorbis.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_mat4.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_sd2.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_w64.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_flac.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_alsa.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_amr_wb.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_mat5.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_wavpack.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_paf.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_amr_nb.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_xi.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/sox/libsox_fmt_caf.so', 'bin/'),
              ('/usr/lib/x86_64-linux-gnu/libsoxr.so.0', 'bin/'),]
elif sys.platform == "win32":
    BINARIES=[('c:\\projects\\make_noise\\bin\\libflac-8.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libgcc_s_sjlj-1.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libgomp-1.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libid3tag-0.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libogg-0.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libpng16-16.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libsox-3.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libssp-0.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libvorbis-0.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libvorbisenc-2.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libvorbisfile-3.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libwavpack-1.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\libwinpthread-1.dll', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\sox.exe', 'bin/'),
              ('c:\\projects\\make_noise\\bin\\zlib1.dll', 'bin/'),]

a = Analysis(['make_noise.py'],
             pathex=[],
             binaries=BINARIES,
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='make_noise',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False, )
# coll = COLLECT(exe,
#                a.binaries,
#                a.zipfiles,
#                a.datas,
#                strip=False,
#                upx=True,
#                upx_exclude=[],
#                name='make_noise')
